#
# golang client to modbusd
#
FROM takawang/psmb:armhf # TODO
MAINTAINER Taka Wang <taka@cmwang.net>

WORKDIR /go
RUN go get -u github.com/taka-wang/psmb

## Load app files
ADD . /go/src/github.com/taka-wang/dummy-psmbtcp
RUN cd /go/src/github.com/taka-wang/dummy-psmbtcp && go get -t ./...

## Default command
CMD ["go", "test", "-v"]
