modbusd: cJSON.h File Reference
cJSON.h File Reference
#include "stdint.h"
Data Structures
struct cJSON
struct cJSON_Hooks
Macros
#define cJSON_False (1 << 0)
#define cJSON_True (1 << 1)
#define cJSON_NULL (1 << 2)
#define cJSON_Number (1 << 3)
#define cJSON_String (1 << 4)
#define cJSON_Array (1 << 5)
#define cJSON_Object (1 << 6)
#define cJSON_IsReference 256
#define cJSON_StringIsConst 512
#define cJSON_AddNullToObject(object, name) cJSON_AddItemToObject(object, name, cJSON_CreateNull())
#define cJSON_AddTrueToObject(object, name) cJSON_AddItemToObject(object, name, cJSON_CreateTrue())
#define cJSON_AddFalseToObject(object, name) cJSON_AddItemToObject(object, name, cJSON_CreateFalse())
#define cJSON_AddBoolToObject(object, name, b) cJSON_AddItemToObject(object, name, cJSON_CreateBool(b))
#define cJSON_AddNumberToObject(object, name, n) cJSON_AddItemToObject(object, name, cJSON_CreateNumber(n))
#define cJSON_AddStringToObject(object, name, s) cJSON_AddItemToObject(object, name, cJSON_CreateString(s))
#define cJSON_SetIntValue(object, val) ((object)?(object)->valueint=(object)->valuedouble=(val):(val))
#define cJSON_SetNumberValue(object, val) ((object)?(object)->valueint=(object)->valuedouble=(val):(val))
#define cJSON_ArrayForEach(pos, head) for(pos = (head)->child; pos != NULL; pos = pos->next)
Typedefs
typedef struct cJSON cJSON
typedef struct cJSON_Hooks cJSON_Hooks
Functions
void cJSON_InitHooks (cJSON_Hooks *hooks)
cJSON * cJSON_Parse (const char *value)
char * cJSON_Print (cJSON *item)
char * cJSON_PrintUnformatted (cJSON *item)
char * cJSON_PrintBuffered (cJSON *item, int prebuffer, int fmt)
void cJSON_Delete (cJSON *c)
int cJSON_GetArraySize (cJSON *array)
cJSON * cJSON_GetArrayItem (cJSON *array, int item)
cJSON * cJSON_GetObjectItem (cJSON *object, const char *string)
int cJSON_HasObjectItem (cJSON *object, const char *string)
const char * cJSON_GetErrorPtr (void)
cJSON * cJSON_CreateNull (void)
cJSON * cJSON_CreateTrue (void)
cJSON * cJSON_CreateFalse (void)
cJSON * cJSON_CreateBool (int b)
cJSON * cJSON_CreateNumber (double num)
cJSON * cJSON_CreateString (const char *string)
cJSON * cJSON_CreateArray (void)
cJSON * cJSON_CreateObject (void)
cJSON * cJSON_CreateUInt8Array (const uint8_t *numbers, int count)
cJSON * cJSON_CreateUInt16Array (const uint16_t *numbers, int count)
cJSON * cJSON_CreateIntArray (const int *numbers, int count)
cJSON * cJSON_CreateFloatArray (const float *numbers, int count)
cJSON * cJSON_CreateDoubleArray (const double *numbers, int count)
cJSON * cJSON_CreateStringArray (const char **strings, int count)
void cJSON_AddItemToArray (cJSON *array, cJSON *item)
void cJSON_AddItemToObject (cJSON *object, const char *string, cJSON *item)
void cJSON_AddItemToObjectCS (cJSON *object, const char *string, cJSON *item)
void cJSON_AddItemReferenceToArray (cJSON *array, cJSON *item)
void cJSON_AddItemReferenceToObject (cJSON *object, const char *string, cJSON *item)
cJSON * cJSON_DetachItemFromArray (cJSON *array, int which)
void cJSON_DeleteItemFromArray (cJSON *array, int which)
cJSON * cJSON_DetachItemFromObject (cJSON *object, const char *string)
void cJSON_DeleteItemFromObject (cJSON *object, const char *string)
void cJSON_InsertItemInArray (cJSON *array, int which, cJSON *newitem)
void cJSON_ReplaceItemInArray (cJSON *array, int which, cJSON *newitem)
void cJSON_ReplaceItemInObject (cJSON *object, const char *string, cJSON *newitem)
cJSON * cJSON_Duplicate (cJSON *item, int recurse)
cJSON * cJSON_ParseWithOpts (const char *value, const char **return_parse_end, int require_null_terminated)
void cJSON_Minify (char *json)
Macro Definition Documentation
#define cJSON_AddBoolToObject (object, name, b) cJSON_AddItemToObject(object, name, cJSON_CreateBool(b))
#define cJSON_AddFalseToObject (object, name) cJSON_AddItemToObject(object, name, cJSON_CreateFalse())
#define cJSON_AddNullToObject (object, name) cJSON_AddItemToObject(object, name, cJSON_CreateNull())
#define cJSON_AddNumberToObject (object, name, n) cJSON_AddItemToObject(object, name, cJSON_CreateNumber(n))
Referenced by mbtcp_get_response_timeout(), and test_json_encode().
#define cJSON_AddStringToObject (object, name, s) cJSON_AddItemToObject(object, name, cJSON_CreateString(s))
Referenced by mbtcp_get_response_timeout(), mbtcp_set_response_timeout(), set_modbus_fail_resp_str(), set_modbus_success_resp_str_with_data(), and test_json_encode().
#define cJSON_AddTrueToObject (object, name) cJSON_AddItemToObject(object, name, cJSON_CreateTrue())
#define cJSON_Array (1 << 5)
Referenced by cJSON_CreateArray(), cJSONUtils_ApplyPatches(), cJSONUtils_FindPointerFromObjectTo(), and cJSONUtils_GetPointer().
#define cJSON_ArrayForEach (pos, head) for(pos = (head)->child; pos != NULL; pos = pos->next)
#define cJSON_False (1 << 0)
Referenced by cJSON_CreateBool(), and cJSON_CreateFalse().
#define cJSON_IsReference 256
Referenced by cJSON_Delete(), and cJSON_Duplicate().
#define cJSON_NULL (1 << 2)
Referenced by cJSON_CreateNull(), and cJSONUtils_MergePatch().
#define cJSON_Number (1 << 3)
Referenced by cJSON_CreateNumber(), cJSON_CreateUInt16(), and cJSON_CreateUInt8().
#define cJSON_Object (1 << 6)
Referenced by cJSON_CreateObject(), cJSONUtils_FindPointerFromObjectTo(), cJSONUtils_GenerateMergePatch(), cJSONUtils_GetPointer(), and cJSONUtils_MergePatch().
#define cJSON_SetIntValue (object, val) ((object)?(object)->valueint=(object)->valuedouble=(val):(val))
#define cJSON_SetNumberValue (object, val) ((object)?(object)->valueint=(object)->valuedouble=(val):(val))
#define cJSON_String (1 << 4)
Referenced by cJSON_CreateString().
#define cJSON_StringIsConst 512
Referenced by cJSON_AddItemToObjectCS(), and cJSON_Delete().
#define cJSON_True (1 << 1)
Referenced by cJSON_CreateBool(), and cJSON_CreateTrue().
Typedef Documentation
typedef struct cJSON cJSON
typedef struct cJSON_Hooks cJSON_Hooks
Function Documentation
void cJSON_AddItemReferenceToArray (cJSON * array, cJSON * item)
References cJSON_AddItemToArray().
 {cJSON_AddItemToArray(array,create_reference(item));}
void cJSON_AddItemReferenceToObject (cJSON * object, const char * string, cJSON * item)
References cJSON_AddItemToObject().
 {cJSON_AddItemToObject(object,string,create_reference(item));}
void cJSON_AddItemToArray (cJSON * array, cJSON * item)
References cJSON::child, and cJSON::next.
Referenced by cJSON_AddItemReferenceToArray(), cJSON_AddItemToObject(), cJSON_AddItemToObjectCS(), and cJSON_InsertItemInArray().
 {cJSON *c=array->child;if (!item) return; if (!c) {array->child=item;} else {while (c && c->next) c=c->next; suffix_object(c,item);}}
void cJSON_AddItemToObject (cJSON * object, const char * string, cJSON * item)
References cJSON_AddItemToArray(), and cJSON::string.
Referenced by cJSON_AddItemReferenceToObject(), cJSONUtils_GenerateMergePatch(), cJSONUtils_MergePatch(), set_modbus_success_resp_str_with_data(), and test_json_encode().
 {if (!item) return; if (item->string) cJSON_free(item->string);item->string=cJSON_strdup(string);cJSON_AddItemToArray(object,item);}
void cJSON_AddItemToObjectCS (cJSON * object, const char * string, cJSON * item)
References cJSON_AddItemToArray(), cJSON_StringIsConst, cJSON::string, and cJSON::type.
 {if (!item) return; if (!(item->type&cJSON_StringIsConst) && item->string) cJSON_free(item->string);item->string=(char*)string;item->type|=cJSON_StringIsConst;cJSON_AddItemToArray(object,item);}
cJSON* cJSON_CreateArray (void)
References cJSON_Array, and cJSON::type.
Referenced by cJSON_CreateDoubleArray(), cJSON_CreateFloatArray(), cJSON_CreateIntArray(), cJSON_CreateStringArray(), cJSON_CreateUInt16Array(), cJSON_CreateUInt8Array(), and cJSONUtils_GeneratePatches().
 {cJSON *item=cJSON_New_Item();if(item)item->type=cJSON_Array;return item;}
cJSON* cJSON_CreateBool (int b)
References cJSON_False, cJSON_True, and cJSON::type.
 {cJSON *item=cJSON_New_Item();if(item)item->type=b?cJSON_True:cJSON_False;return item;}
cJSON* cJSON_CreateDoubleArray (const double * numbers, int count)
References cJSON_CreateArray(), cJSON_CreateNumber(), and cJSON_Delete().
 {int i;cJSON *n=0,*p=0,*a=cJSON_CreateArray();for(i=0;a && i<count;i++){n=cJSON_CreateNumber(numbers[i]);if(!n){cJSON_Delete(a);return 0;}if(!i)a->child=n;else suffix_object(p,n);p=n;}return a;}
cJSON* cJSON_CreateFalse (void)
References cJSON_False, and cJSON::type.
 {cJSON *item=cJSON_New_Item();if(item)item->type=cJSON_False;return item;}
cJSON* cJSON_CreateFloatArray (const float * numbers, int count)
References cJSON_CreateArray(), cJSON_CreateNumber(), and cJSON_Delete().
 {int i;cJSON *n=0,*p=0,*a=cJSON_CreateArray();for(i=0;a && i<count;i++){n=cJSON_CreateNumber(numbers[i]);if(!n){cJSON_Delete(a);return 0;}if(!i)a->child=n;else suffix_object(p,n);p=n;}return a;}
cJSON* cJSON_CreateIntArray (const int * numbers, int count)
References cJSON_CreateArray(), cJSON_CreateNumber(), and cJSON_Delete().
Referenced by test_json_encode().
 {int i;cJSON *n=0,*p=0,*a=cJSON_CreateArray();for(i=0;a && i<count;i++){n=cJSON_CreateNumber(numbers[i]);if(!n){cJSON_Delete(a);return 0;}if(!i)a->child=n;else suffix_object(p,n);p=n;}return a;}
cJSON* cJSON_CreateNull (void)
References cJSON_NULL, and cJSON::type.
Referenced by cJSONUtils_GenerateMergePatch().
 {cJSON *item=cJSON_New_Item();if(item)item->type=cJSON_NULL;return item;}
cJSON* cJSON_CreateNumber (double num)
References cJSON_Number, cJSON::type, cJSON::valuedouble, and cJSON::valueint.
Referenced by cJSON_CreateDoubleArray(), cJSON_CreateFloatArray(), and cJSON_CreateIntArray().
 {cJSON *item=cJSON_New_Item();if(item){item->type=cJSON_Number;item->valuedouble=num;item->valueint=(long)num;}return item;}
cJSON* cJSON_CreateObject (void)
References cJSON_Object, and cJSON::type.
Referenced by cJSONUtils_GenerateMergePatch(), cJSONUtils_MergePatch(), mbtcp_get_response_timeout(), mbtcp_set_response_timeout(), set_modbus_fail_resp_str(), set_modbus_success_resp_str_with_data(), and test_json_encode().
 {cJSON *item=cJSON_New_Item();if(item)item->type=cJSON_Object;return item;}
cJSON* cJSON_CreateString (const char * string)
References cJSON_Delete(), cJSON_String, cJSON::type, and cJSON::valuestring.
Referenced by cJSON_CreateStringArray().
 {cJSON *item=cJSON_New_Item();if(item){item->type=cJSON_String;item->valuestring=cJSON_strdup(string);if(!item->valuestring){cJSON_Delete(item);return 0;}}return item;}
cJSON* cJSON_CreateStringArray (const char ** strings, int count)
References cJSON_CreateArray(), cJSON_CreateString(), and cJSON_Delete().
 {int i;cJSON *n=0,*p=0,*a=cJSON_CreateArray();for(i=0;a && i<count;i++){n=cJSON_CreateString(strings[i]);if(!n){cJSON_Delete(a);return 0;}if(!i)a->child=n;else suffix_object(p,n);p=n;}return a;}
cJSON* cJSON_CreateTrue (void)
References cJSON_True, and cJSON::type.
 {cJSON *item=cJSON_New_Item();if(item)item->type=cJSON_True;return item;}
cJSON* cJSON_CreateUInt16Array (const uint16_t * numbers, int count)
References cJSON_CreateArray(), cJSON_CreateUInt16(), and cJSON_Delete().
Referenced by mbtcp_read_reg_req().
 {int i;cJSON *n=0,*p=0,*a=cJSON_CreateArray();for(i=0;a && i<count;i++){n=cJSON_CreateUInt16(numbers[i]);if(!n){cJSON_Delete(a);return 0;}if(!i)a->child=n;else suffix_object(p,n);p=n;}return a;}
cJSON* cJSON_CreateUInt8Array (const uint8_t * numbers, int count)
References cJSON_CreateArray(), cJSON_CreateUInt8(), and cJSON_Delete().
Referenced by mbtcp_read_bit_req().
 {int i;cJSON *n=0,*p=0,*a=cJSON_CreateArray();for(i=0;a && i<count;i++){n=cJSON_CreateUInt8(numbers[i]);if(!n){cJSON_Delete(a);return 0;}if(!i)a->child=n;else suffix_object(p,n);p=n;}return a;}
void cJSON_Delete (cJSON * c)
References cJSON::child, cJSON_Delete(), cJSON_IsReference, cJSON_StringIsConst, cJSON::next, cJSON::string, cJSON::type, and cJSON::valuestring.
Referenced by cJSON_CreateDoubleArray(), cJSON_CreateFloatArray(), cJSON_CreateIntArray(), cJSON_CreateString(), cJSON_CreateStringArray(), cJSON_CreateUInt16Array(), cJSON_CreateUInt8Array(), cJSON_Delete(), cJSON_DeleteItemFromArray(), cJSON_DeleteItemFromObject(), cJSON_Duplicate(), cJSON_ParseWithOpts(), cJSON_ReplaceItemInArray(), cJSONUtils_GenerateMergePatch(), cJSONUtils_MergePatch(), main(), mbtcp_get_response_timeout(), mbtcp_set_response_timeout(), set_modbus_fail_resp_str(), set_modbus_success_resp_str_with_data(), test_json_decode(), and test_json_encode().
 {
     cJSON *next;
     while (c)
     {
         next=c->next;
         if (!(c->type&cJSON_IsReference) && c->child) cJSON_Delete(c->child);
         if (!(c->type&cJSON_IsReference) && c->valuestring) cJSON_free(c->valuestring);
         if (!(c->type&cJSON_StringIsConst) && c->string) cJSON_free(c->string);
         cJSON_free(c);
         c=next;
     }
 }
void cJSON_DeleteItemFromArray (cJSON * array, int which)
References cJSON_Delete(), and cJSON_DetachItemFromArray().
 {cJSON_Delete(cJSON_DetachItemFromArray(array,which));}
void cJSON_DeleteItemFromObject (cJSON * object, const char * string)
References cJSON_Delete(), and cJSON_DetachItemFromObject().
Referenced by cJSONUtils_MergePatch().
 {cJSON_Delete(cJSON_DetachItemFromObject(object,string));}
cJSON* cJSON_DetachItemFromArray (cJSON * array, int which)
References cJSON::child, cJSON::next, and cJSON::prev.
Referenced by cJSON_DeleteItemFromArray(), and cJSON_DetachItemFromObject().
                                                                     {cJSON *c=array->child;while (c && which>0) c=c->next,which--;if (!c) return 0;
     if (c->prev) c->prev->next=c->next;if (c->next) c->next->prev=c->prev;if (c==array->child) array->child=c->next;c->prev=c->next=0;return c;}
cJSON* cJSON_DetachItemFromObject (cJSON * object, const char * string)
References cJSON::child, cJSON_DetachItemFromArray(), cJSON::next, and cJSON::string.
Referenced by cJSON_DeleteItemFromObject(), and cJSONUtils_MergePatch().
 {int i=0;cJSON *c=object->child;while (c && cJSON_strcasecmp(c->string,string)) i++,c=c->next;if (c) return cJSON_DetachItemFromArray(object,i);return 0;}
cJSON* cJSON_Duplicate (cJSON * item, int recurse)
References cJSON::child, cJSON_Delete(), cJSON_Duplicate(), cJSON_IsReference, cJSON::next, cJSON::prev, cJSON::string, cJSON::type, cJSON::valuedouble, cJSON::valueint, and cJSON::valuestring.
Referenced by cJSON_Duplicate(), cJSONUtils_GenerateMergePatch(), and cJSONUtils_MergePatch().
 {
     cJSON *newitem,*cptr,*nptr=0,*newchild;
     /* Bail on bad ptr */
     if (!item) return 0;
     /* Create new item */
     newitem=cJSON_New_Item();
     if (!newitem) return 0;
     /* Copy over all vars */
     newitem->type=item->type&(~cJSON_IsReference),newitem->valueint=item->valueint,newitem->valuedouble=item->valuedouble;
     if (item->valuestring)  {newitem->valuestring=cJSON_strdup(item->valuestring);  if (!newitem->valuestring)  {cJSON_Delete(newitem);return 0;}}
     if (item->string)       {newitem->string=cJSON_strdup(item->string);            if (!newitem->string)       {cJSON_Delete(newitem);return 0;}}
     /* If non-recursive, then we're done! */
     if (!recurse) return newitem;
     /* Walk the ->next chain for the child. */
     cptr=item->child;
     while (cptr)
     {
         newchild=cJSON_Duplicate(cptr,1);       /* Duplicate (with recurse) each item in the ->next chain */
         if (!newchild) {cJSON_Delete(newitem);return 0;}
         if (nptr)   {nptr->next=newchild,newchild->prev=nptr;nptr=newchild;}    /* If newitem->child already set, then crosswire ->prev and ->next and move on */
         else        {newitem->child=newchild;nptr=newchild;}                    /* Set newitem->child and move to it */
         cptr=cptr->next;
     }
     return newitem;
 }
cJSON* cJSON_GetArrayItem (cJSON * array, int item)
References cJSON::child, and cJSON::next.
Referenced by cJSONUtils_GetPointer(), mbtcp_multi_write_req(), and test_json_decode().
 {cJSON *c=array?array->child:0;while (c && item>0) item--,c=c->next; return c;}
int cJSON_GetArraySize (cJSON * array)
References cJSON::child, and cJSON::next.
Referenced by mbtcp_multi_write_req(), and test_json_decode().
 {cJSON *c=array->child;int i=0;while(c)i++,c=c->next;return i;}
const char* cJSON_GetErrorPtr (void)
 {return global_ep;}
cJSON* cJSON_GetObjectItem (cJSON * object, const char * string)
References cJSON::child, cJSON::next, and cJSON::string.
Referenced by cJSON_HasObjectItem(), json_get_char(), json_get_double(), json_get_int(), json_get_long(), json_set_double(), json_set_int(), mbtcp_multi_write_req(), and test_json_decode().
 {cJSON *c=object?object->child:0;while (c && cJSON_strcasecmp(c->string,string)) c=c->next; return c;}
int cJSON_HasObjectItem (cJSON * object, const char * string)
References cJSON_GetObjectItem().
 {return cJSON_GetObjectItem(object,string)?1:0;}
void cJSON_InitHooks (cJSON_Hooks * hooks)
References cJSON_Hooks::free_fn, and cJSON_Hooks::malloc_fn.
 {
     if (!hooks) { /* Reset hooks */
         cJSON_malloc = malloc;
         cJSON_free = free;
         return;
     }
     cJSON_malloc = (hooks->malloc_fn)?hooks->malloc_fn:malloc;
     cJSON_free   = (hooks->free_fn)?hooks->free_fn:free;
 }
void cJSON_InsertItemInArray (cJSON * array, int which, cJSON * newitem)
References cJSON::child, cJSON_AddItemToArray(), cJSON::next, and cJSON::prev.
                                                                             {cJSON *c=array->child;while (c && which>0) c=c->next,which--;if (!c) {cJSON_AddItemToArray(array,newitem);return;}
     newitem->next=c;newitem->prev=c->prev;c->prev=newitem;if (c==array->child) array->child=newitem; else newitem->prev->next=newitem;}
void cJSON_Minify (char * json)
 {
     char *into=json;
     while (*json)
     {
         if (*json==' ') json++;
         else if (*json=='\t') json++;   /* Whitespace characters. */
         else if (*json=='\r') json++;
         else if (*json=='\n') json++;
         else if (*json=='/' && json[1]=='/')  while (*json && *json!='\n') json++;  /* double-slash comments, to end of line. */
         else if (*json=='/' && json[1]=='*') {while (*json && !(*json=='*' && json[1]=='/')) json++;json+=2;}   /* multiline comments. */
         else if (*json=='\"'){*into++=*json++;while (*json && *json!='\"'){if (*json=='\\') *into++=*json++;*into++=*json++;}*into++=*json++;} /* string literals, which are \" sensitive. */
         else *into++=*json++;           /* All other characters. */
     }
     *into=0;    /* and null-terminate. */
 }
cJSON* cJSON_Parse (const char * value)
References cJSON_ParseWithOpts().
Referenced by file_to_json(), main(), and test_json_decode().
 {return cJSON_ParseWithOpts(value,0,0);}
cJSON* cJSON_ParseWithOpts (const char * value, const char ** return_parse_end, int require_null_terminated)
References cJSON_Delete().
Referenced by cJSON_Parse().
 {
     const char *end=0,**ep=return_parse_end?return_parse_end:&global_ep;
     cJSON *c=cJSON_New_Item();
     *ep=0;
     if (!c) return 0;       /* memory fail */
     end=parse_value(c,skip(value),ep);
     if (!end)   {cJSON_Delete(c);return 0;} /* parse failure. ep is set. */
     /* if we require null-terminated JSON without appended garbage, skip and then check for a null terminator */
     if (require_null_terminated) {end=skip(end);if (*end) {cJSON_Delete(c);*ep=end;return 0;}}
     if (return_parse_end) *return_parse_end=end;
     return c;
 }
char* cJSON_Print (cJSON * item)
Referenced by json_to_file(), test_json_decode(), and test_json_encode().
 {return print_value(item,0,1,0);}
char* cJSON_PrintBuffered (cJSON * item, int prebuffer, int fmt)
References printbuffer::buffer, printbuffer::length, and printbuffer::offset.
 {
     printbuffer p;
     p.buffer=(char*)cJSON_malloc(prebuffer);
     p.length=prebuffer;
     p.offset=0;
     return print_value(item,0,fmt,&p);
 }
char* cJSON_PrintUnformatted (cJSON * item)
Referenced by mbtcp_get_response_timeout(), mbtcp_set_response_timeout(), set_modbus_fail_resp_str(), and set_modbus_success_resp_str_with_data().
 {return print_value(item,0,0,0);}
void cJSON_ReplaceItemInArray (cJSON * array, int which, cJSON * newitem)
References cJSON::child, cJSON_Delete(), cJSON::next, and cJSON::prev.
Referenced by cJSON_ReplaceItemInObject().
                                                                             {cJSON *c=array->child;while (c && which>0) c=c->next,which--;if (!c) return;
     newitem->next=c->next;newitem->prev=c->prev;if (newitem->next) newitem->next->prev=newitem;
     if (c==array->child) array->child=newitem; else newitem->prev->next=newitem;c->next=c->prev=0;cJSON_Delete(c);}
void cJSON_ReplaceItemInObject (cJSON * object, const char * string, cJSON * newitem)
References cJSON::child, cJSON_ReplaceItemInArray(), cJSON::next, and cJSON::string.
 {int i=0;cJSON *c=object->child;while(c && cJSON_strcasecmp(c->string,string))i++,c=c->next;if(c){newitem->string=cJSON_strdup(string);cJSON_ReplaceItemInArray(object,i,newitem);}}