modbusd: json.h File Reference
json.h File Reference
cJSON helper functions header
#include "json/cJSON.h"
Functions
char * json_get_char (cJSON *inJson, const char *key)
Get char string via key from cJSON object.
int json_get_int (cJSON *inJson, const char *key)
Get integer value via key from cJSON object.
void json_set_int (cJSON *inJson, const char *key, int value)
Set integer value via key to existed cJSON object.
double json_get_double (cJSON *inJson, const char *key)
Get double integer value via key from cJSON object.
void json_set_double (cJSON *inJson, const char *key, double value)
Set double integer value via key to existed cJSON object.
long json_get_long (cJSON *inJson, const char *key)
Get long integer value via key from cJSON object.
int file_to_json (const char *fname, cJSON **outJson)
Load JSON file to cJSON object.
int json_to_file (const char *fname, cJSON *inJson)
Save cJSON object to JSON file.
Detailed Description
cJSON helper functions header
Author
Taka Wang
Function Documentation
int file_to_json (const char * fname, cJSON ** outJson)
Load JSON file to cJSON object.
Parameters
fname File name string.
outJson Pointer to cJSON output object.
Returns
Success or not.
References cJSON_Parse().
 {
     FILE *fPtr = fopen(fname,"rb");
     if (fPtr)
     {
         fseek(fPtr, 0, SEEK_END);
         long len = ftell(fPtr);
         fseek(fPtr, 0, SEEK_SET);
         char *data = (char*) malloc (len+1);
         int _ = fread(data, 1, len, fPtr); _=_;
         fclose(fPtr);
         *outJson = cJSON_Parse(data);
         free(data);
         return outJson ? 0 : 1;
     }
     else
     {
         return -1;
     }
 }
char* json_get_char (cJSON * inJson, const char * key)
Get char string via key from cJSON object.
Parameters
inJson cJSON object.
key Json key.
Returns
C char string.
References cJSON_GetObjectItem(), and cJSON::valuestring.
Referenced by main(), and mbtcp_cmd_hanlder().
 {
     return cJSON_GetObjectItem(inJson, key)->valuestring;
 }
double json_get_double (cJSON * inJson, const char * key)
Get double integer value via key from cJSON object.
Parameters
inJson cJSON object.
key Json key.
Returns
Double integer value.
References cJSON_GetObjectItem(), and cJSON::valuedouble.
 {
     return cJSON_GetObjectItem(inJson, key)->valuedouble;
 }
int json_get_int (cJSON * inJson, const char * key)
Get integer value via key from cJSON object.
Parameters
inJson cJSON object.
key Json key.
Returns
Integer.
References cJSON_GetObjectItem(), and cJSON::valueint.
Referenced by main(), and mbtcp_cmd_hanlder().
 {
     return cJSON_GetObjectItem(inJson, key)->valueint;
 }
long json_get_long (cJSON * inJson, const char * key)
Get long integer value via key from cJSON object.
Parameters
inJson cJSON object.
key Json key.
Returns
Long.
References cJSON_GetObjectItem(), and cJSON::valuedouble.
Referenced by main().
 {
     // convert double float to long integer
     return (long)cJSON_GetObjectItem(inJson, key)->valuedouble;
 }
void json_set_double (cJSON * inJson, const char * key, double value)
Set double integer value via key to existed cJSON object.
Parameters
inJson cJSON object.
key Json key.
double Double integer value.
Returns
Void.
References cJSON_GetObjectItem(), and cJSON::valuedouble.
 {
     cJSON_GetObjectItem(inJson, key)->valuedouble = value;
 }
void json_set_int (cJSON * inJson, const char * key, int value)
Set integer value via key to existed cJSON object.
Parameters
inJson cJSON object.
key Json key.
value Integer value.
Returns
Void.
References cJSON_GetObjectItem(), and cJSON::valueint.
 {
     cJSON_GetObjectItem(inJson, key)->valueint = value;
 }
int json_to_file (const char * fname, cJSON * inJson)
Save cJSON object to JSON file.
Parameters
fname File name string.
inJson cJSON input object.
Returns
Success or not.
References cJSON_Print().
 {
     FILE *fPtr = fopen(fname, "w");
     if (fPtr)
     {
         fprintf(fPtr, "%s", cJSON_Print(inJson));
         fclose(fPtr);
         return 0;
     }
     else
     {
         return -1;
     }
 }