modbusd: mb.c File Reference
mb.c File Reference
modbus common functions
#include "mb.h"
Functions
char * set_modbus_success_resp_str (char *tid)
Set modbusd success response string without data (i.e., write func)
char * set_modbus_success_resp_str_with_data (char *tid, cJSON *json_arr)
Set modbusd success response string with data (i.e., read func)
char * set_modbus_fail_resp_str (char *tid, const char *reason)
Set modbusd fail response string.
char * set_modbus_fail_resp_str_with_errno (char *tid, mbtcp_handle_s *handle, int errnum)
Set modbusd fail response string with error number.
Variables
int enable_syslog
Detailed Description
modbus common functions
Author
Taka Wang
Function Documentation
char* set_modbus_fail_resp_str (char * tid, const char * reason)
Set modbusd fail response string.
Parameters
tid Transaction ID.
reason Fail reason string.
Returns
Modbus response string in JSON format.
References BEGIN, cJSON_AddStringToObject, cJSON_CreateObject(), cJSON_Delete(), cJSON_PrintUnformatted(), enable_syslog, END, ERR, and LOG.
Referenced by main(), mbtcp_cmd_hanlder(), and set_modbus_fail_resp_str_with_errno().
 {
     BEGIN(enable_syslog);
     ERR(enable_syslog, "fail: %s", reason);
     cJSON *resp_root;
     resp_root = cJSON_CreateObject();
     cJSON_AddStringToObject(resp_root, "tid", tid);
     cJSON_AddStringToObject(resp_root, "status", reason);
     char * resp_json_string = cJSON_PrintUnformatted(resp_root);
     LOG(enable_syslog, "resp: %s", resp_json_string);
     // clean up
     cJSON_Delete(resp_root);
     END(enable_syslog);
     return resp_json_string;
 }
char* set_modbus_fail_resp_str_with_errno (char * tid, mbtcp_handle_s * handle, int errnum)
Set modbusd fail response string with error number.
Parameters
tid Transaction ID.
handle Mbtcp handle.
errnum Error number from modbus tcp handle.
Returns
Modbus error response string in JSON format.
References BEGIN, mbtcp_handle_s::connected, enable_syslog, END, ERR, and set_modbus_fail_resp_str().
 {
     BEGIN(enable_syslog);
     // [TODO][enhance] reconnect proactively?
     // ... if the request interval is very large,
     // we should try to reconnect automatically
     if (errnum == 104) // Connection reset by peer (i.e, tcp connection timeout)
     {
         handle->connected = false;
     }
     ERR(enable_syslog, "%s:%d", modbus_strerror(errnum), errnum);
     END(enable_syslog);
     return set_modbus_fail_resp_str(tid, modbus_strerror(errnum));
 }
char* set_modbus_success_resp_str (char * tid)
Set modbusd success response string without data (i.e., write func)
Parameters
tid Transaction ID.
Returns
Modbus ok response string in JSON format.
References BEGIN, cJSON_AddStringToObject, cJSON_CreateObject(), cJSON_Delete(), cJSON_PrintUnformatted(), enable_syslog, END, and LOG.
 {
     BEGIN(enable_syslog);
     cJSON *resp_root;
     resp_root = cJSON_CreateObject();
     cJSON_AddStringToObject(resp_root, "tid", tid);
     cJSON_AddStringToObject(resp_root, "status", "ok");
     char * resp_json_str = cJSON_PrintUnformatted(resp_root);
     LOG(enable_syslog, "resp: %s", resp_json_str);
     // clean up
     cJSON_Delete(resp_root);
     END(enable_syslog);
     return resp_json_str;
 }
char* set_modbus_success_resp_str_with_data (char * tid, cJSON * json_arr)
Set modbusd success response string with data (i.e., read func)
Parameters
tid Transaction ID.
json_arr cJSON pointer to data array
Returns
Modbus ok response string in JSON format.
References BEGIN, cJSON_AddItemToObject(), cJSON_AddStringToObject, cJSON_CreateObject(), cJSON_Delete(), cJSON_PrintUnformatted(), enable_syslog, END, and LOG.
 {
     BEGIN(enable_syslog);
     cJSON *resp_root;
     resp_root = cJSON_CreateObject();
     cJSON_AddStringToObject(resp_root, "tid", tid);
     cJSON_AddItemToObject(resp_root, "data", json_arr);
     cJSON_AddStringToObject(resp_root, "status", "ok");
     char * resp_json_str = cJSON_PrintUnformatted(resp_root);
     LOG(enable_syslog, "resp: %s", resp_json_str);
     // clean up
     cJSON_Delete(resp_root);
     END(enable_syslog);
     return resp_json_str;
 }
Variable Documentation
int enable_syslog
Referenced by set_modbus_fail_resp_str(), set_modbus_fail_resp_str_with_errno(), set_modbus_success_resp_str(), and set_modbus_success_resp_str_with_data().